## NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.Numpy has many built-in functions and capabilities. 

In [9]:
import numpy as np


## Numpy Arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

### Creating NumPy Arrays
#### From a Python List
We can create an array by directly converting a list or list of lists:

In [10]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [11]:
np.array(my_list)

array([1, 2, 3])

In [12]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods
There are lots of built-in ways to generate Arrays

#### arange
Return evenly spaced values within a given interval.

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

#### Zeros and ones
Generate arrays of zeros or ones

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace
Return evenly spaced numbers over a specified interval.

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye
Creates an identity matrix


In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
Numpy also has lots of ways to create random numbers arrays:

#### rand

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).


In [25]:
np.random.rand(2)

array([0.69373644, 0.3386054 ])

In [26]:
np.random.rand(5, 5)

array([[0.85126167, 0.45239846, 0.57934852, 0.29212872, 0.49333816],
       [0.69279489, 0.70597838, 0.58170646, 0.43797913, 0.64063989],
       [0.11288798, 0.38204164, 0.03224264, 0.49868976, 0.70620763],
       [0.79044087, 0.93618736, 0.21861859, 0.53049704, 0.43633483],
       [0.73263287, 0.29140466, 0.54487893, 0.43131148, 0.19646218]])

#### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [27]:
np.random.randn(2)

array([-1.94168449,  0.33273555])

In [28]:
np.random.randn(5, 5)

array([[-1.02832763, -0.06167319,  0.76940126, -0.29683063,  2.21279593],
       [ 0.1215529 ,  1.17861309, -0.20034481, -0.77786384,  0.72658073],
       [ 0.99758465,  0.99237512,  0.68282806, -1.18220614,  0.35277375],
       [ 0.23256749, -0.53802303,  0.59261708, -0.3119246 , -0.41621075],
       [ 0.60928667, -0.76983303,  0.35904465,  0.68952582, -0.37802858]])

#### randint

Return random integers from low (inclusive) to high (exclusive).


In [30]:
np.random.randint(1, 100)

26

In [31]:
np.random.randint(1, 100, 10)

array([61, 76, 41, 20, 35, 32, 70, 70, 47, 88])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([35,  9, 41, 33,  1,  3, 33, 39, 40, 14])

## Reshape

Returns an array containing the same data with a new shape

In [35]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin
this are useful method for finding max or min values. Or to find there index locations using argmin or argmax

In [40]:
ranarr

array([35,  9, 41, 33,  1,  3, 33, 39, 40, 14])

In [41]:
ranarr.max()

41

In [42]:
ranarr.argmax()

2

In [44]:
ranarr.min()

1

In [45]:
ranarr.argmin()

4

### Shape
Shape is an attributes that arrays have (not a method)

In [46]:
# vector
arr.shape

(25,)

In [47]:
# Notice two set of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(1, 25).shape

(1, 25)

In [49]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [50]:
arr.reshape(25, 1).shape

(25, 1)

## dtype
You can also grab the data type of the object in the array:

In [51]:
arr.dtype

dtype('int32')