## Numpy Indexing and Selection
How to select elements or groups of elements from an array

In [9]:
import numpy as np

In [10]:
# creating sample array
arr = np.arange(0, 11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

The simplest way to pick one or some elements of an array look very similar to python lists:

In [12]:
# Get a value at an index
arr[8]

np.int64(8)

In [13]:
#Get values in an range
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting
Numpy array differ from a normal python list because of their ability to broadcast:

In [15]:
# Setting a value with index range (Broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# Reset array, we'll see I why had to reset in a moment
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Important note on slices 
slices_of_arr = arr[0:6]
slices_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
#Change slices 
slices_of_arr[:] = 99
slices_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row, col]. 

In [22]:
arr_2d  = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# Indexing row
arr_2d[1]

array([20, 25, 30])

In [24]:
# Format is arr_2d[row][col] or arr_2d[row, col]

#Getting individual element value
arr_2d[1][0]

np.int64(20)

In [25]:
arr_2d[1,0]

np.int64(20)

In [26]:
# 2D array slicing
# shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#shape bottom row
arr_2d[2]

array([35, 40, 45])

In [30]:
arr_2d[2, :]

array([35, 40, 45])

## Fancy indexing
Fancy indexing allow you to select entire row or columns out of order, to show this, let's quickly build out a numpy array:

In [37]:
#Set up matrix
arr2d = np.zeros((10, 10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
# Length of array 
arr_length = arr2d.shape[1]
arr_length

10

In [39]:
# Set up array
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

fancy indexing allows the following

In [40]:
arr2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [41]:
# Allows in any order
arr2d[[6, 4, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More indexing Help

Indexing a 2d matrix can be a bit confusing at  first, especially when you start to add in step size. Try google image searching NumPy indexing to finds useful images.

### Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [43]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
x = 2
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])